name: Test
on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable --silent

      - name: Check types
        run: yarn run type-check

      - name: Check lint
        run: yarn run lint

      - name: Build
        run: yarn run build
